# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7_withVBGA"

  config.vbguest.auto_update = true

  config.vm.hostname = "DevISM.local"
  config.vm.network :public_network, bridge: "en0: Wi-Fi (AirPort)"

  config.vm.post_up_message = "Heyooo!"

  config.vm.provision "chef_solo" do |chef|
    chef.add_recipe "apache"
  end

end
