# -*- mode: ruby -*-
# vi: set ft=ruby :

HOSTNAME = 'DevISM.local'

$UpMsg = <<UPMSG
---------------------------------------------------------------------
Local iSM Dev Server, running headless (i.e. in the background)
Type "vagrant ssh" to access via SSH

iSM 8 running on CentOS 7

URLS:
 ---- iSM Console ------> http://#{HOSTNAME}:9999
---------------------------------------------------------------------
UPMSG

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7_withVBGA"
  config.vbguest.auto_update = true

  config.vm.provider 'virtualbox' do |vb|
  	vb.memory = '1024'
  	vb.cpus = '1'
  end

  config.vm.hostname = HOSTNAME
  config.vm.network :public_network, bridge: "en0: Wi-Fi (AirPort)"

  config.vm.post_up_message = $UpMsg

  config.vm.provision "chef_solo" do |chef|
    chef.add_recipe "iWay8::default"
    chef.add_recipe "iWay8::mDNS"
    chef.add_recipe "iWay8::JDK1_8"
    chef.add_recipe "iWay8::iSM8"
  end

end
